version: '3'

services:

  vtiger:
    build: ${VERSION_DIR}/${VERSION}
    environment:
      - VT_DEBUG=false
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./:/app
      - ./tests/volume:/var/lib/vtiger:rw
    links:
      - mysql
      - adminer

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql:rw
      - ./:/vtiger:rw

  adminer:
    image: javanile/adminer
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 8081:8080
    links:
      - mysql

volumes:
  mysql:
