version: '3'

services:

  vtiger:
    build: ${VERSION_DIR}/${VERSION}
    environment:
      - VT_DEBUG=false
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./:/app
      - ./tmp/volume:/var/lib/vtiger:rw
    links:
      - mysql
      - adminer

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./:/vtiger:rw
      - mysql:/var/lib/mysql:rw

  adminer:
    image: javanile/adminer
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 8082:8080
    links:
      - mysql

  contrib:
    build: ./contrib
    volumes:
      - ./:/vtiger

volumes:
  mysql:
