version: '2'

services:

  vtiger:
    image: javanile/vtiger:${version:-latest}
    build: ${version}
    environment:
      - VT_DEBUG=false
      - VT_INSTALL=${install}
      - LOG4PHP_DEBUG=false
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 20080:80
      - 20443:443
    volumes:
      - ./:/app
      - ./vtiger:/var/lib/vtiger
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
      - adminer

  adminer:
    image: javanile/adminer
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 20081:8080
    links:
      - mysql

  mysql:
    image: ${database}
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql:rw
      - ./:/vtiger:rw
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  script:
    image: debian
    working_dir: /app
    command: bash -c "echo 'prevent default'; exit 0"
    volumes:
      - ./:/app:rw

volumes:
  mysql:
