/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'Vtiger-icons\'">' + entity + '</span>' + html;
	}
	var icons = {
		'vicon-accounts': '&#xe600;',
		'vicon-add': '&#xe601;',
		'vicon-alert': '&#xe602;',
		'vicon-assets': '&#xe603;',
		'vicon-attachment': '&#xe604;',
		'vicon-autoresponder': '&#xe605;',
		'vicon-bell': '&#xe606;',
		'vicon-bulb': '&#xe607;',
		'vicon-calendar': '&#xe608;',
		'vicon-calendaragenda': '&#xe609;',
		'vicon-calendarlist': '&#xe60a;',
		'vicon-call': '&#xe60b;',
		'vicon-camera': '&#xe60c;',
		'vicon-campaigns': '&#xe60d;',
		'vicon-cases': '&#xe60e;',
		'vicon-chat': '&#xe60f;',
		'vicon-close': '&#xe610;',
		'vicon-code': '&#xe611;',
		'vicon-codebraces': '&#xe612;',
		'vicon-cog': '&#xe613;',
		'vicon-columns': '&#xe614;',
		'vicon-compose': '&#xe615;',
		'vicon-contacts': '&#xe616;',
		'vicon-customerportal': '&#xe617;',
		'vicon-default': '&#xe618;',
		'vicon-detailreport': '&#xe619;',
		'vicon-documents': '&#xe61a;',
		'vicon-duplicaterecords': '&#xe61b;',
		'vicon-edit': '&#xe61c;',
		'vicon-emailcampaigns': '&#xe61d;',
		'vicon-emails': '&#xe61e;',
		'vicon-emailtemplates': '&#xe61f;',
		'vicon-engagementhistory': '&#xe620;',
		'vicon-equalizer': '&#xe621;',
		'vicon-esign': '&#xe622;',
		'vicon-exit': '&#xe623;',
		'vicon-export': '&#xe624;',
		'vicon-eyeclose': '&#xe625;',
		'vicon-eyeopen': '&#xe626;',
		'vicon-faq': '&#xe627;',
		'vicon-fb': '&#xe628;',
		'vicon-folderclose': '&#xe629;',
		'vicon-foldermove': '&#xe62a;',
		'vicon-folderopen': '&#xe62b;',
		'vicon-forecast': '&#xe62c;',
		'vicon-forward': '&#xe62d;',
		'vicon-googleplus': '&#xe62e;',
		'vicon-graphview': '&#xe62f;',
		'vicon-grid': '&#xe630;',
		'vicon-help': '&#xe631;',
		'vicon-helpdesk': '&#xe632;',
		'vicon-home': '&#xe633;',
		'vicon-image': '&#xe634;',
		'vicon-import': '&#xe635;',
		'vicon-insights': '&#xe636;',
		'vicon-inventory': '&#xe637;',
		'vicon-inventory2': '&#xe638;',
		'vicon-inventory3': '&#xe639;',
		'vicon-invoice': '&#xe63a;',
		'vicon-invoicerecurring': '&#xe63b;',
		'vicon-leads': '&#xe63c;',
		'vicon-link': '&#xe63d;',
		'vicon-linkopen': '&#xe63e;',
		'vicon-list': '&#xe63f;',
		'vicon-lock': '&#xe640;',
		'vicon-lockopen': '&#xe641;',
		'vicon-logout': '&#xe642;',
		'vicon-mailmanager': '&#xe643;',
		'vicon-mandatory': '&#xe644;',
		'vicon-marketinglist': '&#xe645;',
		'vicon-massedit': '&#xe646;',
		'vicon-meeting': '&#xe647;',
		'vicon-move': '&#xe648;',
		'vicon-mycalendar': '&#xe649;',
		'vicon-olark': '&#xe64a;',
		'vicon-olark2': '&#xe64b;',
		'vicon-oursites': '&#xe64c;',
		'vicon-pagecount': '&#xe64d;',
		'vicon-payments': '&#xe64e;',
		'vicon-pbxmanager': '&#xe64f;',
		'vicon-phonecalls': '&#xe650;',
		'vicon-pin': '&#xe651;',
		'vicon-pivots': '&#xe652;',
		'vicon-play': '&#xe653;',
		'vicon-potentials': '&#xe654;',
		'vicon-pricebooks': '&#xe655;',
		'vicon-printtemplates': '&#xe656;',
		'vicon-products': '&#xe657;',
		'vicon-project': '&#xe658;',
		'vicon-projectmilestone': '&#xe659;',
		'vicon-projecttask': '&#xe65a;',
		'vicon-purchaseorder': '&#xe65b;',
		'vicon-puzzle': '&#xe65c;',
		'vicon-quickbooks': '&#xe65d;',
		'vicon-quotes': '&#xe65e;',
		'vicon-recyclebin': '&#xe65f;',
		'vicon-refresh': '&#xe660;',
		'vicon-replytoall': '&#xe661;',
		'vicon-reports': '&#xe662;',
		'vicon-restorerecyclebin': '&#xe663;',
		'vicon-retweet': '&#xe664;',
		'vicon-road': '&#xe665;',
		'vicon-rss': '&#xe666;',
		'vicon-salesorder': '&#xe667;',
		'vicon-search': '&#xe668;',
		'vicon-selectcolumn': '&#xe669;',
		'vicon-servicecontracts': '&#xe66a;',
		'vicon-services': '&#xe66b;',
		'vicon-share': '&#xe66c;',
		'vicon-sharedcalendar': '&#xe66d;',
		'vicon-shoppingcart': '&#xe66e;',
		'vicon-smiley1': '&#xe66f;',
		'vicon-smiley2': '&#xe670;',
		'vicon-smiley3': '&#xe671;',
		'vicon-smsnotifier': '&#xe672;',
		'vicon-social': '&#xe673;',
		'vicon-starempty': '&#xe674;',
		'vicon-starfull': '&#xe675;',
		'vicon-starhalf': '&#xe676;',
		'vicon-subscription': '&#xe677;',
		'vicon-tag': '&#xe678;',
		'vicon-task': '&#xe679;',
		'vicon-taxes': '&#xe67a;',
		'vicon-timeline': '&#xe67b;',
		'vicon-toggle': '&#xe67c;',
		'vicon-transactions': '&#xe67d;',
		'vicon-twitter': '&#xe67e;',
		'vicon-twitterreply': '&#xe67f;',
		'vicon-unpin': '&#xe680;',
		'vicon-unplug': '&#xe681;',
		'vicon-vendors': '&#xe682;',
		'vicon-vendors3': '&#xe683;',
		'vicon-video': '&#xe684;',
		'vicon-volumeoff': '&#xe685;',
		'vicon-volumeon': '&#xe686;',
		'vicon-vtigeruser': '&#xe687;',
		'vicon-vtigeruser2': '&#xe688;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/vicon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
